services:
  app:
    container_name: server_working
    build:
      context: .  # Specifies the build context as the current directory (.)
      dockerfile: Dockerfile
    environment:
      env_file: ".env"
    ports:
      - "8081:8081"
    volumes:
      - .:/app # The first line (.:/app) ensures you can edit files on your host machine, and the changes will reflect immediately inside the container.
      - /app/node_modules # The second line (/app/node_modules) prevents issues related to mismatched Node.js environments between the host and the container.
    depends_on:
      - db

  db :
    container_name : postgres_server
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data,
  pgadmin :
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    depends_on :
      - db
volumes:
  postgres_data: